communitiesuk/prsdb-infra

- ReadMe.md
- terraform/integration/main.tf
- terraform/modules/frontdoor/load_balancer.tf
- terraform/modules/frontdoor/outputs.tf
- terraform/modules/frontdoor/variables.tf
- terraform/modules/networking/firewall.tf
- terraform/modules/networking/outputs.tf
- terraform/modules/networking/variables.tf
First PR for PRSD-573 to add the alb - this will be rebased onto main once PRSD-572 is merged
> PRSD-573: Adds load balancer

- terraform/integration/.terraform.lock.hcl
- terraform/integration/main.tf
- terraform/integration/outputs.tf
- terraform/integration/variables.tf
- terraform/modules/frontdoor/cloudfront.tf
- terraform/modules/frontdoor/load_balancer.tf
- terraform/modules/frontdoor/main.tf
- terraform/modules/frontdoor/outputs.tf
- terraform/modules/frontdoor/variables.tf
- terraform/modules/networking/gateways.tf
To be rebased onto main after the multiple AZs PR has merged
> PRSD-573: Adds Cloudfront and updates ALB

- ReadMe.md
- terraform/integration/backend/main.tf
- terraform/integration/main.tf
- terraform/integration/outputs.tf
- terraform/modules/frontdoor/cloudfront.tf
- terraform/modules/frontdoor/load_balancer.tf
- terraform/modules/networking/firewall.tf
- terraform/modules/networking/gateways.tf
- terraform/modules/networking/outputs.tf
- terraform/modules/networking/route_table.tf
- terraform/modules/networking/subnet.tf
+ adds prevent destroys
Small intermediate PR covering AZ change
> PRSD-573: Reverts to single AZ for firewall, updates ReadMe

- .github/workflows/check-and-plan.yml
- terraform/integration/main.tf
- terraform/integration/variables.tf
- terraform/modules/ecr/ecr.tf
To be rebased onto main once SSL changes have merged.
> feat/PRSD-571: Adds plan job in pipeline

- terraform/modules/ecr/iam.tf
- terraform/modules/ecr/outputs.tf
First of several small PRs with resources required for the task definition
> PRSD-752: Adds task role

- .github/workflows/update-task-definition.yml
Workflow to be called by other workflows (incl. by the webapp build & deploy workflow) that updates the task definition
> PRSD-752: Adds callable task definition workflow

- ReadMe.md
- terraform/integration/ecs_task_definition/main.tf
- terraform/integration/main.tf
- terraform/modules/ecr/outputs.tf
- terraform/modules/secrets/iam.tf
- terraform/modules/secrets/kms.tf
- terraform/modules/secrets/main.tf
- terraform/modules/secrets/outputs.tf
- terraform/modules/secrets/secrets.tf
- terraform/modules/secrets/variables.tf
Separate PR for SSM parameters to follow
> PRSD-790: Creates application secrets

- terraform/modules/secrets/iam.tf
PR #24 ran into a slightly esoteric KMS issue on `terraform apply` - this should be the fix (cribbed from Core)
> PRSD-790: Fixes broken iam policy document

- terraform/integration/main.tf
Adds the SSM module to the environment
> PRSD-790: Adds SSM params to environment

- terraform/integration/main.tf
Fix for the tf apply error run into in PR #28
> PRSD-790: Fixes number of isolated subnets to 2

- terraform/integration/ecs_task_definition/main.tf
- terraform/modules/ecs_task/logging.tf
- terraform/modules/ecs_task/task_definition.tf
Some changes required to the ECS task definition to allow the task to run and be debugged
> PRSD-751: Adds logging and changes user in ECS task

- ReadMe.md
- setup/create_profiles.ps1
- setup/create_profiles.sh
- setup/profile-template
Adds installation and setup instructions for terraform and aws-vault and provides a shell script to configure profiles.
> PRSD-762: Add terraform set up documentation

- ReadMe.md
Capitalise references to PATH variable.
Adds instructions for installing the Session Manager plugin.
> PRSD-898: Add getting Session Manager plugin to readme instructions

- terraform/modules/file_upload/main.tf
Resolves issue where deployed service cannot put files to encrypted S3 bucket.
> PRSD-1001: Allow ecs to generate key data and encrypt

- .github/workflows/apply-integration.yml
- .github/workflows/apply-test.yml
- .github/workflows/apply.yml
- .github/workflows/check-and-plan-integration.yml
- .github/workflows/check-and-plan-test.yml
- .github/workflows/check-and-plan.yml
- .github/workflows/validate-target-environment.yml
- Parameterizes `apply.yml` on environment
- Creates `apply-integration.yml` and `apply-test.yml`
- Parameterizes `check-and-plan.yml` on environment
- Creates `check-and-plan-integration.yml` and `check-and-plan-test.yml`
- Creates `validate-target-environment.yml` and uses it in `apply.yml` and `check-and-plan.yml`
> PRSD-969: Parameterize Infra Pipeline

- .github/workflows/apply-integration.yml
- .github/workflows/apply-test.yml
Enables reporting of pipeline status to Slack
> PRSD-969: Allows apply.yml to inherit integration and test secrets

- .github/workflows/apply-integration.yml
- .github/workflows/apply-test.yml
- .github/workflows/apply.yml
- .github/workflows/check-and-plan-integration.yml
- .github/workflows/check-and-plan-test.yml
- .github/workflows/check-and-plan.yml
- .github/workflows/validate-target-environment.yml
- ReadMe.md
- terraform/environment_template/ecs_task_definition/data.tf.template
- terraform/environment_template/ecs_task_definition/main.tf.template
- terraform/environment_template/main.tf.template
- terraform/environment_template/terraform.tfvars.template
- terraform/integration/ecs_task_definition/data.tf
- terraform/integration/ecs_task_definition/main.tf
- terraform/integration/main.tf
- terraform/modules/bastion/instance.tf
- terraform/modules/file_upload/main.tf
- terraform/modules/file_upload/parameters.tf
- terraform/modules/file_upload/variables.tf
- terraform/modules/networking/vpc_endpoints.tf
- terraform/test/ecs_task_definition/data.tf
- terraform/test/ecs_task_definition/main.tf
- terraform/test/main.tf
Includes:
- Adding quarantine s3 bucket (PRSD-1000 & PRSD-1001)
- Adding s3 VPC endpoints (PRSD-NONE)
- Adding name tag to bastion hosts (PRSD-NONE)
- Adding deployment pipeline for `Test` environment
- Updating ReadMe (PRSD-968)
> Release main to test #1

- terraform/modules/file_upload/main.tf
Add a decrypt permission to the S3 kms key used for file uploads.
> PRSD-1002: Add decrypt permission to allow upload

- terraform/modules/frontdoor/waf.tf
For the moment I've targetted all urls containing "file-upload" to test that this works as expected. We can refine the rule (and probably commonise the statment to ensure that it's always applied) in a later PR.
> PRSD-1001: Update WAF rules for file-upload

- terraform/modules/frontdoor/waf.tf
As discussed yesterday, switch to using a custom rule to detect large requests to make it harder to accidentally exclude requests from AWS common WAF protection (and to reduce total number of rules).
> PRSD-1001: Handle size constraints in custom rule

- terraform/modules/frontdoor/waf.tf
This release includes:
- Update WAF rules for file-upload ([PRSD-1001](https://mhclgdigital.atlassian.net/browse/PRSD-1001))
- Handle size constraints in custom rule ([PRSD-1001](https://mhclgdigital.atlassian.net/browse/PRSD-1001))
- Add testable rule to block large file uploads ([PRSD-1003](https://mhclgdigital.atlassian.net/browse/PRSD-1003))
- Do not accept overly large files ([PRSD-1003](https://mhclgdigital.atlassian.net/browse/PRSD-1003))
> Release main to test #3

- terraform/modules/elasticache/redis.tf
- terraform/modules/rds/kms.tf
- terraform/modules/rds/rds.tf
This will be rebased onto main once the PR for adding redis logging is merged.
> PRSD-733: Adds performance insights to rds

- terraform/modules/secrets/iam.tf
Oops - missed this change when updating the secrets module.
> PRSD-1065: Add secret to access list

- terraform/integration/main.tf
- terraform/test/main.tf
I've just added it to Integration - we'll need to do the same for Test at some point.
> PRSD-1065: Add EPC register to integration domains

- terraform/environment_template/ecs_task_definition/data.tf.template
- terraform/environment_template/ecs_task_definition/main.tf.template
- terraform/integration/ecs_task_definition/data.tf
- terraform/integration/ecs_task_definition/main.tf
- terraform/modules/ssm/parameters.tf
- terraform/test/ecs_task_definition/data.tf
- terraform/test/ecs_task_definition/main.tf
Add an epc_certificate_base_url ssm parameter
> PRSD-1132: Add epc-certificate-base-url ssm parameter

- ReadMe.md
- terraform/environment_template/ecs_task_definition/data.tf.template
- terraform/environment_template/ecs_task_definition/main.tf.template
- terraform/environment_template/main.tf.template
- terraform/integration/ecs_task_definition/data.tf
- terraform/integration/ecs_task_definition/main.tf
- terraform/integration/main.tf
- terraform/modules/file_upload/virus_scanning.tf
- terraform/modules/frontdoor/cloudfront.tf
- terraform/modules/frontdoor/variables.tf
- terraform/modules/ssm/parameters.tf
- terraform/test/ecs_task_definition/data.tf
- terraform/test/ecs_task_definition/main.tf
- terraform/test/main.tf
This release includes:
- PRSD-1132: Add epc-certificate-base-user ssm parameter
- PRSD-948: Add virus scanning
- PRSD-1295: unblock secondary domain on cloudfront
> Release main to test #7

- terraform/environment_template/main.tf.template
- terraform/integration/main.tf
- terraform/modules/ecs_service/outputs.tf
- terraform/modules/file_upload/variables.tf
- terraform/modules/file_upload/virus_scanning.tf
- terraform/test/main.tf
For sure before this ticket is done I will split up that massive monster file that is virus_scanning, but I want to see if this actually works first!
> PRSD-1282: Add example ecs task to virus scan events

- terraform/modules/frontdoor/url_rewriter.js
Quick update to add id-verification, login and logout as an exception
> PRSD-1294: Add id-verification as an exception

- terraform/modules/frontdoor/url_rewriter.js
> PRSD-1294: Add oauth2 exception

- terraform/modules/file_upload/safe_bucket.tf
PRSD-976
Gives the service permission to get objects and their versions from S3 so that it can create presigned urls.
> PRSD-976: Give the service download permissions for safe files

- terraform/test/ecs_task_definition/main.tf
Temporarily turning off passcodes in test for today
> PRSD-NONE: Temporarily turn off passcodes in test

- .github/workflows/apply.yml
- .github/workflows/check-and-plan.yml
- ReadMe.md
- terraform/integration/main.tf
- terraform/integration/variables.tf
- terraform/modules/monitoring/alarms.tf
- terraform/modules/monitoring/cloudtrail.tf
- terraform/modules/monitoring/iam.tf
- terraform/modules/monitoring/kms.tf
- terraform/modules/monitoring/main.tf
- terraform/modules/monitoring/metrics.tf
- terraform/modules/monitoring/s3.tf
- terraform/modules/monitoring/sns.tf
- terraform/modules/monitoring/variables.tf
- terraform/modules/networking/vpc_endpoints.tf
- terraform/production/main.tf
- terraform/production/variables.tf
- terraform/test/main.tf
- terraform/test/variables.tf
- PRSD-1178: Adds cloudwatch alarms for AWS access
> Release main to test #14

- .github/workflows/apply.yml
PRSD-1531
Add slack reporting for test and production builds
Removed the is branch "main" from the re porting on slack action
I have not tested this manually
N/A
> PRSD-1531: Add slack reporting for test and production builds

- .github/workflows/update-task-definition.yml
PRSD-1509
Makes 'Update task definition` GitHub workflow checkout the target environment's corresponding branch
As above
N/A
> PRSD-1509: Makes pipeline target task definition on right branch

- terraform/modules/frontdoor/cloudfront.tf
PRSD-1075
Fix resource declaration for cloudfront shield advanced
As above
N/A
N/A
> PRSD-1075: Fix resource declaration for cloudfront shield advanced

- terraform/modules/frontdoor/load_balancer_waf.tf
PRSD-1075
Remove `provider` declaration and update name to be more prcise
As above
N/A
N/A
> PRSD-1075: Fix load balancer waf acl region and name
