communitiesuk/prsdb-infra

- terraform/environment_template/main.tf.template
- terraform/environment_template/outputs.tf.template
- terraform/integration/main.tf
- terraform/integration/outputs.tf
- terraform/modules/networking/firewall.tf
- terraform/modules/networking/outputs.tf
- terraform/modules/networking/route_table.tf
- terraform/modules/networking/subnet.tf
- terraform/modules/networking/variables.tf
Switching to multiple AZs for public and private subnets (isolated subnet still tied to whether RDS is using multi-AZ, which we might not want to do in `integration` for cost purposes). ADR to updated in [the open webapp PR](https://github.com/communitiesuk/prsdb-webapp/pull/85).
> PRSD-573: Switches to multiple AZs

- terraform/integration/main.tf
- terraform/modules/ecr/ecr.tf
Some tweaks were required to keep AWS happy once I set `ssl_certs_created` to `true`. In particular, if we want to use tagged
> PRSD-NONE: Adds missing params to allow alb & cf to be updated with SSL

- terraform/modules/github_actions_access/iam.tf
Allows webapp repo to assume plan & apply roles, and also fixes a matching issue on OIDC access that affects both Apply and ECR push. Note: Because this would have prevented the Apply step from completing it has been terraform applied manually.
> PRSD-748: Updates OIDC iam policy to allow access from webapp

- ReadMe.md
- terraform/integration/ecs_task_definition/data.tf
- terraform/integration/ecs_task_definition/main.tf
- terraform/modules/secrets/kms.tf
- terraform/modules/ssm/main.tf
- terraform/modules/ssm/parameters.tf
- terraform/modules/ssm/variables.tf
To be rebased and targeted at main when PR #24 is merged. Includes a small tidying up of the task definition module. There is a bigger refactor I'd like to do to parameterize the task definition module and move it to `./modules` but I'll do that in a separate PR once we have finished adding to it.
> PRSD-790: Adds SSM parameters

- terraform/modules/elasticache/redis.tf
7.1 is the current maximum version supported by elasticache https://docs.aws.amazon.com/AmazonElastiCache/latest/dg/supported-engine-versions.html#supported-engine-versions.redis
> PRSD-751: Changes Redis version to 7.1

- terraform/integration/main.tf
- terraform/modules/networking/outputs.tf
- terraform/modules/networking/subnet.tf
It seems aws distinguishes between different subnet group types and I missed this.
(I have also terraform applied this locally to make sure there are no more gotchas from this ticket...)
> PRSD-751: Uses correct subnet group type for redis

- terraform/environment_template/main.tf.template
- terraform/integration/main.tf
- terraform/modules/file_upload/main.tf
- terraform/modules/file_upload/variables.tf
- terraform/test/main.tf
I've added the S3 bucket directly to each main tf file. There are two things I'm unsure of here:
* Should I actually make a module for "file_uploads" (or something) and add the S3 bucket to that instead
* There are a few values that I've just left as their default values that I should maybe set (but I wouldn't know what to)
* kms_key_arn - KMS key to encrypt bucket and access logs bucket
* noncurrent_version_expiration_days - not sure what this is for
* policy - Don't know if there's a reason we'd need anything past the default bucket enforce ssl policy
* object_lock_enabled - defaults to false. Don't know what we'd user AWS Object Lock for
> PRSD-1000: Add quarantine S3 bucket

- terraform/modules/frontdoor/waf.tf
This includes the rule as intended, but with a couple of differences - the max size is 10MB not 1GB and the redirect location is the dashboard.
My intention is that we merge this to test everything with sensible files and without waiting for a new endpoint to be deployed then can update those values at our leasure.
> PRSD-1003: Add testable rule to block large file uploads

- .github/workflows/pull_request_template.md
Add a pull request template (largely copied from the webapp repo) including a checklist action to document special release actions (such as environment variables that will need setting)
QQ: is there some github setup required so that this gets used?
> PRSD-none: Add a pull_request_template

- terraform/modules/frontdoor/url_rewriter.js
If I try and test the deployed function I'm getting "The CloudFront function associated with the CloudFront distribution is invalid or could not run. Entry point function "handler" is not found"
So maybe it _has_ to be called handler...
> PRSD-1294: Re-name main function to "handler"

- terraform/modules/frontdoor/url_rewriter.js
- test/js/url_rewriter.test.js
PRSD-1167
Make the cookies page endpoint reachable by making it exempt from URL rewriting
- Adds the cookies page to the array of endpoints exempt from URL rewriting 
N/A
> PRSD-1167: Makes the cookies page endpoint reachable

- terraform/modules/frontdoor/UrlRewriterReadMe.md
- terraform/modules/frontdoor/url_rewriter.js
- test/js/url_rewriter.test.js
PRSD-1355
Update urls to be local council instead of local authority
Update url_rewriter.js to use "local-council" instead of "local-authority"
Updated tests
This PR should be merged at the same time or just after the equivalent webapp PR (not yet created)
N/A
> PRSD-1355: update urls to be local council instead of local authority

- terraform/modules/file_upload/scan_result_processing.tf
PRSD-1352
Adds the etag and version id of objects to the environment variables available during a virus scan so that we can ensure we can find and update the correct record for the file in the database.
> PRSD-1352: Add more file details to scan variables

- terraform/environment_template/ecs_task_definition/data.tf.template
- terraform/environment_template/ecs_task_definition/main.tf.template
- terraform/integration/ecs_task_definition/data.tf
- terraform/integration/ecs_task_definition/main.tf
- terraform/modules/ssm/parameters.tf
- terraform/test/ecs_task_definition/data.tf
- terraform/test/ecs_task_definition/main.tf
PRSD-1183
Pass in analytics ids as environment variables so we can use a different id for prod when it comes
Added
- plausible analytics domain id
- google analytics measurement id
- google analytics cookie domain (we need this to delete cookies if a user changes their preferences to reject cookies)
Make sure to include details such as the name of the variable, where it needs to be set (e.g. AWS Secrets Manager or Parameter Store), and what it should be set to (this might be a location in keeper where a secret value can be found)
> PRSD-1183: Add environment variables for analytics domain ids

- terraform/environment_template/ecs_task_definition/data.tf.template
- terraform/environment_template/ecs_task_definition/main.tf.template
- terraform/integration/ecs_task_definition/data.tf
- terraform/integration/ecs_task_definition/main.tf
- terraform/modules/ssm/parameters.tf
- terraform/production/ecs_task_definition/data.tf
- terraform/production/ecs_task_definition/main.tf
- terraform/test/ecs_task_definition/data.tf
- terraform/test/ecs_task_definition/main.tf
PRSD-NONE
Hotfix to create environment variable for One Login DID URL
As we're not yet live this hotifx will go directly to production, and then merged back down production->test, test->main (with normal non-squash merges).
The value will be set in each environment before we roll out the Webapp hotifx that relies on it.
Also temporarily turning off passcodes for convenience until prod is fully smoke tested (have already verified these are working).
> PRSD-NONE: Adds environment variable for One Login DID URL

- terraform/modules/monitoring/kms.tf
PRSD-1178
Removes circular dependency in Cloudtrail kms policy that was preventing the creation of our cloudtrail
Summary of the changes made. These should focus on the functionality that you've changed rather than the actual code
changes - those will be clear from the PR.
E.g. Prefer "Adds new endpoint for uploading gas safety certificates to s3" to "Adds new `UploadGasSafetyCertificate`
controller that accepts a `UploadFileRequest` and uses the `fileUploadService` to upload the file to s3"
As part of debugging this has already been applied to integration
> PRSD-1178: Removes circular dependency in kms policy

- terraform/production/ecs_task_definition/main.tf
- terraform/test/ecs_task_definition/main.tf
PRSD-1166
Turn on require-passcode profile in prod and test environments
As above
N/A
> PRSD-1166: Turn on require-passcode profile in prod and test

- terraform/modules/monitoring/alarms.tf
- terraform/modules/monitoring/metrics.tf
PRSD-1178
Fire an alarm when someone either logs in via AWS Console or AWS Vault
Replace ConsoleLogin alarm with AssumeRoleWithSaml alarm. The ConsoleLogin event was only firing when a user logs in on AWS Console, but AssumeRoleWithSaml fires when someone assumes a role from the console or the vault.
This is untested, do I need to change anything else? Are there any release actions to make the alarm send an email?
Make sure to include details such as the name of the variable, where it needs to be set (e.g. AWS Secrets Manager or Parameter Store), and what it should be set to (this might be a location in keeper where a secret value can be found)
> PRSD-1178: Replace ConsoleLogin alarm with AssumeRoleWithSaml alarm

- terraform/modules/frontdoor/url_rewriter.js
- test/js/url_rewriter.test.js
PRSD-1491
Create a maintenance page that users are re-directed to if the service has been taken down
Exclude the "maintenance" endpoint from url_rewriter
> PRSD-1491: Exclude maintenance endpoint from url_rewriter

- terraform/environment_template/main.tf.template
- terraform/integration/main.tf
- terraform/modules/bastion/iam.tf
- terraform/modules/bastion/logging.tf
- terraform/modules/bastion/ssm_patch.tf
- terraform/modules/bastion/variables.tf
- terraform/production/main.tf
- terraform/test/main.tf
PRSD-981
Add SSM patch manager to patch the bastion host
- Add some built in ssm policies to the existing aws_iam_role.ssm_bastion
- Sets up a maintenance window when patching will be done (set to 2am on wednesday mornings - I'm hoping this would be a quiet time!)
- Add a task to run "AWS-RunPatchBaseline" in the maintenance window
- this should run the default baseline patches for the operating system of the bastion, in our case this is AWS-AmazonLinux2DefaultPatchBaseline
- From [docs](https://docs.aws.amazon.com/systems-manager/latest/userguide/patch-manager-predefined-and-custom-patch-baselines.html), this `Approves all operating system patches that are classified as "Security" and that have a severity level of "Critical" or "Important". Also approves all patches with a classification …
> Feat/prsd 981 - ssm patch manager for bastions

- terraform/environment_template/main.tf.template
- terraform/integration/main.tf
- terraform/modules/ecs_service/outputs.tf
- terraform/modules/elasticache/outputs.tf
- terraform/modules/frontdoor/outputs.tf
- terraform/modules/monitoring/cloudwatch.tf
- terraform/modules/monitoring/metrics.tf
- terraform/modules/monitoring/resource_alarms.tf
- terraform/modules/monitoring/variables.tf
- terraform/modules/rds/outputs.tf
- terraform/production/main.tf
- terraform/test/main.tf
PRSD-1526
Adds CloudWatch alarms for resource metrics
- Created CloudWatch alarms for:
- High ECS CPU usage
- High ECS memory usage
- ECS task failing to start (also added corresponding log group and metric)
- High RDS instance CPU usage
- Low RDS storage space
- High Elasticache CPU usage
- Low Elasticache storage space
- Persistent 5xx codes reaching the ALB
- Persistent 4xx codes reaching the ALB
- No healthy ALB hosts
- Persistent WAF block actions
N/A
> PRSD-1526: Resource Metric CloudWatch Alarms

- .github/workflows/update-ecs-service.yml
PRSD-1537
Creates GitHub workflow for updating the ECS service
As above
- An webapp PR will be created that refactors current workflows with 'update ECS service' jobs to call this workflow
- Although all current 'update ECS service' jobs are in the webapp repo, this ticket involves creating an infra pipeline that'll have one, so the workflow has been placed here
> PRSD-1537: Creates update ECS service workflow

- terraform/environment_template/main.tf.template
- terraform/integration/main.tf
- terraform/modules/elasticache/outputs.tf
- terraform/modules/frontdoor/outputs.tf
- terraform/modules/monitoring/cloudwatch.tf
- terraform/modules/monitoring/main.tf
- terraform/modules/monitoring/metrics.tf
- terraform/modules/monitoring/resource_alarms.tf
- terraform/modules/monitoring/sns.tf
- terraform/modules/monitoring/variables.tf
- terraform/modules/rds/outputs.tf
- terraform/production/main.tf
- terraform/test/main.tf
PRSD-1526
Fixes and cleans up CloudWatch alarms
- Fixes incorrect CloudWatch alarm config
- Adds `WizAccess-Role` exemption to alarm for unauthorized API calls
- Treats missing data as ok when appropriate (e.g. when counting errors)
N/A
> PRSD-1526: Fix and Clean-up CloudWatch Alarms

- terraform/environment_template/ecs_task_definition/data.tf.template
- terraform/environment_template/ecs_task_definition/main.tf.template
- terraform/integration/ecs_task_definition/data.tf
- terraform/integration/ecs_task_definition/main.tf
- terraform/modules/secrets/iam.tf
- terraform/modules/secrets/secrets.tf
- terraform/production/ecs_task_definition/data.tf
- terraform/production/ecs_task_definition/main.tf
- terraform/test/ecs_task_definition/data.tf
- terraform/test/ecs_task_definition/main.tf
PRSD-1021
Renames OS API key to be more general
As above
- This ticket prompted the renaming as we'll be using another OS API (with the same key)
- After merging, populate the new tf-integration-os-api-key secret. Go to AWS Console -> Secrets Manager -> tf-integration-os-api-key and set the value (the value can be found in the development .env file in Keeper)
> PRSD-1021: Renames OS API key
